version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Europe/Stockholm'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    reviewers:
      - 'jk'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      dev-dependencies:
        patterns:
          - '*'
        dependency-type: 'development'
      prod-dependencies:
        patterns:
          - '*'
        dependency-type: 'production'
    assignees:
      - 'jk'